### ISSUE TITLE
Add to Milrato and more questions ?

### ISSUE THREAD

**Issue by pasindu20** [Tomato6966/remote-sqlite-database#1]
If this better then quickmongo add this to milrato 
also is this like enmap database ?
how do i create table to each section  ?
Is this work on sharded discord bots ?
Is this database systeam use lot of resoruces ?
Add **Array** method in enmap (get is more complicated to get array)

**Comment by Tomato6966** [comment]
It is a very good remote database based on enmap.

All connected clients are automatically - synced - cached.

It's average ping on 30-50 writes / second for 25 Connected Clients, is between 0 and 1.8ms (Literally just the ping for your ipc connection)

It's rather stable and havent crashed since i've been using it

You could use it in Milrato, Almost without any changes, I will be in need of adding pathing for the key, so that you can use it in milrato too!

To create a "table" just create a second server This is how to create one: 
https://sourceb.in/ijA5lWSl6U
> You can have "infinite" Servers aka Databases, just 1 per Port

It does not use many resources, just the bigger your db the more ram the db needs

There is a push and remove array method, if youdont want to use get and set

**Comment by Tomato6966** [comment]
Example how to connect to it with ease
https://sourceb.in/cSuR0WF2t9

**Comment by Tomato6966** [comment]
from now on, you can use it with milrato sharded instead of quickmongo, just initalize the db and tables with this:
https://sourceb.in/cSuR0WF2t9 and it will work 100% the same as before with no extra changes needed (in theory)
